import type { MixerScene } from "@/types/routing";

export const demoScene: MixerScene = {
  mixerType: "X32/M32",
  fileName: "demo_sunday_service.scn",
  fileSize: 18432,
  parsedAt: new Date().toISOString(),
  status: "Parsed",
  inputs: [
    { number: 1, name: "Kick In", source: "AN 1", dcaAssignments: ["Drums"], color: "YE" },
    { number: 2, name: "Kick Out", source: "AN 2", dcaAssignments: ["Drums"], color: "YE" },
    { number: 3, name: "Snare Top", source: "AN 3", dcaAssignments: ["Drums"], color: "YE" },
    { number: 4, name: "Snare Bot", source: "AN 4", dcaAssignments: ["Drums"], color: "YE" },
    { number: 5, name: "Hi-Hat", source: "AN 5", dcaAssignments: ["Drums"], color: "YE" },
    { number: 9, name: "Bass DI", source: "AN 9", dcaAssignments: ["Band"], color: "GN" },
    { number: 10, name: "Bass Mic", source: "AN 10", dcaAssignments: ["Band"], color: "GN" },
    { number: 11, name: "Elec Gtr L", source: "AN 11", dcaAssignments: ["Band"], color: "RD" },
    { number: 12, name: "Elec Gtr R", source: "AN 12", dcaAssignments: ["Band"], color: "RD" },
    { number: 13, name: "Acoustic", source: "AN 13", dcaAssignments: ["Band"], color: "OR" },
    { number: 14, name: "Keys L", source: "AN 14", dcaAssignments: ["Band"], color: "MG" },
    { number: 15, name: "Keys R", source: "AN 15", dcaAssignments: ["Band"], color: "MG" },
    { number: 17, name: "Vox Lead", source: "AES50A 1", dcaAssignments: ["Vocals"], color: "CY" },
    { number: 18, name: "Vox BGV 1", source: "AES50A 2", dcaAssignments: ["Vocals"], color: "CY" },
    { number: 19, name: "Vox BGV 2", source: "AES50A 3", dcaAssignments: ["Vocals"], color: "CY" },
    { number: 20, name: "Pastor", source: "AES50A 4", dcaAssignments: ["Speech"], color: "WH" },
    { number: 25, name: "Click", source: "CARD 1", dcaAssignments: ["Tracks"], color: "BL" },
    { number: 26, name: "Tracks L", source: "CARD 2", dcaAssignments: ["Tracks"], color: "BL" },
    { number: 27, name: "Tracks R", source: "CARD 3", dcaAssignments: ["Tracks"], color: "BL" },
  ],
  buses: [
    { number: 1, name: "IEM Drums", type: "Mix Bus" },
    { number: 2, name: "IEM Bass", type: "Mix Bus" },
    { number: 3, name: "IEM Gtr", type: "Mix Bus" },
    { number: 4, name: "IEM Keys", type: "Mix Bus" },
    { number: 5, name: "IEM Vox L", type: "Mix Bus" },
    { number: 6, name: "IEM Vox R", type: "Mix Bus" },
    { number: 7, name: "Wedge SR", type: "Mix Bus" },
    { number: 8, name: "Wedge SL", type: "Mix Bus" },
    { number: 11, name: "FX Verb", type: "FX Send" },
    { number: 12, name: "FX Delay", type: "FX Send" },
    { number: 13, name: "Broadcast L", type: "Mix Bus" },
    { number: 14, name: "Broadcast R", type: "Mix Bus" },
  ],
  dcas: [
    { number: 1, name: "Drums", assignedChannels: [1, 2, 3, 4, 5] },
    { number: 2, name: "Band", assignedChannels: [9, 10, 11, 12, 13, 14, 15] },
    { number: 3, name: "Vocals", assignedChannels: [17, 18, 19] },
    { number: 4, name: "Speech", assignedChannels: [20] },
    { number: 5, name: "Tracks", assignedChannels: [25, 26, 27] },
  ],
  outputs: [
    { outputType: "XLR", number: 1, source: "Main L" },
    { outputType: "XLR", number: 2, source: "Main R" },
    { outputType: "XLR", number: 3, source: "Sub" },
    { outputType: "XLR", number: 4, source: "Front Fill" },
    { outputType: "XLR", number: 5, source: "Bus 7 (Wedge SR)" },
    { outputType: "XLR", number: 6, source: "Bus 8 (Wedge SL)" },
    { outputType: "Aux", number: 1, source: "Broadcast L" },
    { outputType: "Aux", number: 2, source: "Broadcast R" },
    { outputType: "AES50-A", number: 1, source: "S16 Stage Inputs 1-16" },
    { outputType: "AES50-A", number: 2, source: "S16 Stage Inputs 17-32" },
    { outputType: "Card", number: 1, source: "Multitrack Record L" },
    { outputType: "Card", number: 2, source: "Multitrack Record R" },
    { outputType: "Ultranet", number: 1, source: "P16 IEM Drums" },
    { outputType: "Ultranet", number: 2, source: "P16 IEM Bass" },
    { outputType: "Matrix", number: 1, source: "Lobby Feed" },
  ],
  routingBlocks: [
    { blockName: "IN", assignments: ["AN1-8", "AN9-16", "AES50A-1-8", "AES50A-9-16", "CARD-1-8"] },
    { blockName: "OUT", assignments: ["MAIN", "AUX1-6", "MTX1-6"] },
    { blockName: "AES50A", assignments: ["S16-1", "S16-2"] },
  ],
  warnings: [],
  unrecognizedLines: [],
};
