import type { MixerScene } from "@/types/routing";

function pad(s: string | number, n: number): string {
  const str = String(s);
  return str.length >= n ? str : str + " ".repeat(n - str.length);
}

function mdTable(headers: string[], rows: (string | number)[][]): string {
  const aligns = headers.map(() => "---");
  const out: string[] = [];
  out.push(`| ${headers.join(" | ")} |`);
  out.push(`| ${aligns.join(" | ")} |`);
  for (const r of rows) {
    out.push(`| ${r.map((c) => String(c ?? "")).join(" | ")} |`);
  }
  return out.join("\n");
}

export function sceneToMarkdown(scene: MixerScene): string {
  const lines: string[] = [];
  lines.push(`# X32 / M32 RouteView — Routing Documentation`);
  lines.push("");
  lines.push(`> Professional scene routing summary generated by RouteView.`);
  lines.push("");
  lines.push(`## Scene Overview`);
  lines.push("");
  lines.push(`| Field | Value |`);
  lines.push(`| --- | --- |`);
  if (scene.fileName) lines.push(`| Source file | \`${scene.fileName}\` |`);
  lines.push(`| Mixer | ${scene.mixerType} |`);
  lines.push(`| Parse status | ${scene.status} |`);
  lines.push(`| Inputs | ${scene.inputs.length} |`);
  lines.push(`| Mix buses | ${scene.buses.length} |`);
  lines.push(`| DCA groups | ${scene.dcas.length} |`);
  lines.push(`| Output patches | ${scene.outputs.length} |`);
  lines.push(`| Generated | ${new Date(scene.parsedAt).toLocaleString()} |`);
  lines.push("");

  lines.push(`---`);
  lines.push("");
  lines.push(`## 1. Input Channels`);
  lines.push("");
  lines.push(
    mdTable(
      ["Ch", "Name", "Source", "DCA", "Color", "Notes"],
      scene.inputs.map((c) => [
        c.number,
        c.name,
        c.source ?? "",
        (c.dcaAssignments ?? []).join(", "),
        c.color ?? "",
        c.notes ?? "",
      ]),
    ),
  );
  lines.push("");

  lines.push(`---`);
  lines.push("");
  lines.push(`## 2. Mix Buses`);
  lines.push("");
  lines.push(
    mdTable(
      ["Bus", "Name", "Type", "Notes"],
      scene.buses.map((b) => [b.number, b.name, b.type ?? "", b.notes ?? ""]),
    ),
  );
  lines.push("");

  lines.push(`---`);
  lines.push("");
  lines.push(`## 3. DCA Groups`);
  lines.push("");
  lines.push(
    mdTable(
      ["DCA", "Name", "Assigned Channels"],
      scene.dcas.map((d) => [d.number, d.name, (d.assignedChannels ?? []).join(", ")]),
    ),
  );
  lines.push("");

  lines.push(`---`);
  lines.push("");
  lines.push(`## 4. Output Patches`);
  lines.push("");
  lines.push(
    mdTable(
      ["Type", "#", "Source", "Notes"],
      scene.outputs.map((o) => [o.outputType, o.number, o.source, o.notes ?? ""]),
    ),
  );
  lines.push("");

  if (scene.routingBlocks.length) {
    lines.push(`---`);
    lines.push("");
    lines.push(`## 5. Routing Blocks`);
    lines.push("");
    for (const r of scene.routingBlocks) {
      lines.push(`- **${r.blockName}** — ${r.assignments.join(", ")}`);
    }
    lines.push("");
  }

  if (scene.warnings.length) {
    lines.push(`---`);
    lines.push("");
    lines.push(`## Warnings`);
    lines.push("");
    for (const w of scene.warnings) lines.push(`- ${w}`);
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`_Generated by X32/M32 RouteView — documentation tool, read-only._`);
  pad; // silence
  return lines.join("\n");
}

function toCSV(rows: (string | number | undefined)[][]): string {
  return rows
    .map((r) =>
      r
        .map((cell) => {
          const s = cell === undefined || cell === null ? "" : String(cell);
          return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
        })
        .join(","),
    )
    .join("\n");
}

/** Single combined CSV with section banners for Inputs / Buses / DCAs / Outputs. */
export function combinedCSV(scene: MixerScene): string {
  const sections: string[] = [];

  sections.push(
    toCSV([
      ["# X32/M32 RouteView — Routing Export"],
      ["# File", scene.fileName ?? ""],
      ["# Mixer", scene.mixerType],
      ["# Status", scene.status],
      ["# Generated", new Date(scene.parsedAt).toISOString()],
    ]),
  );

  sections.push(
    toCSV([
      [],
      ["## INPUTS"],
      ["Channel", "Name", "Source", "DCA", "Color", "Notes"],
      ...scene.inputs.map((c) => [
        c.number,
        c.name,
        c.source ?? "",
        (c.dcaAssignments ?? []).join("; "),
        c.color ?? "",
        c.notes ?? "",
      ]),
    ]),
  );

  sections.push(
    toCSV([
      [],
      ["## BUSES"],
      ["Bus", "Name", "Type", "Notes"],
      ...scene.buses.map((b) => [b.number, b.name, b.type ?? "", b.notes ?? ""]),
    ]),
  );

  sections.push(
    toCSV([
      [],
      ["## DCAs"],
      ["DCA", "Name", "Assigned Channels"],
      ...scene.dcas.map((d) => [d.number, d.name, (d.assignedChannels ?? []).join("; ")]),
    ]),
  );

  sections.push(
    toCSV([
      [],
      ["## OUTPUTS"],
      ["Output Type", "Number", "Source", "Notes"],
      ...scene.outputs.map((o) => [o.outputType, o.number, o.source, o.notes ?? ""]),
    ]),
  );

  return sections.join("\n");
}

export function downloadText(filename: string, contents: string, mime = "text/plain") {
  const blob = new Blob([contents], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
