import type { MixerScene } from "@/types/routing";

/**
 * Print-only routing document. Hidden on screen, only visible in @media print.
 * Renders a professional one-document layout with Inputs, Buses, DCAs and Outputs.
 */
export function PrintView({ scene }: { scene: MixerScene }) {
  const now = new Date(scene.parsedAt).toLocaleString();
  return (
    <div className="print-view hidden print:block">
      <header className="print-header">
        <div>
          <h1>X32 / M32 RouteView</h1>
          <p className="print-sub">Scene Routing Documentation</p>
        </div>
        <div className="print-meta">
          <div><strong>File:</strong> {scene.fileName ?? "—"}</div>
          <div><strong>Mixer:</strong> {scene.mixerType}</div>
          <div><strong>Status:</strong> {scene.status}</div>
          <div><strong>Generated:</strong> {now}</div>
        </div>
      </header>

      <section className="print-summary">
        <Stat label="Inputs" value={scene.inputs.length} />
        <Stat label="Buses" value={scene.buses.length} />
        <Stat label="DCAs" value={scene.dcas.length} />
        <Stat label="Outputs" value={scene.outputs.length} />
      </section>

      <Section title="1. Input Channels">
        <table className="print-table">
          <thead>
            <tr>
              <th style={{ width: "8%" }}>Ch</th>
              <th style={{ width: "26%" }}>Name</th>
              <th style={{ width: "18%" }}>Source</th>
              <th style={{ width: "20%" }}>DCA</th>
              <th style={{ width: "10%" }}>Color</th>
              <th>Notes</th>
            </tr>
          </thead>
          <tbody>
            {scene.inputs.map((c) => (
              <tr key={`in-${c.number}`}>
                <td>{c.number}</td>
                <td>{c.name}</td>
                <td>{c.source ?? ""}</td>
                <td>{(c.dcaAssignments ?? []).join(", ")}</td>
                <td>{c.color ?? ""}</td>
                <td>{c.notes ?? ""}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </Section>

      <Section title="2. Mix Buses">
        <table className="print-table">
          <thead>
            <tr>
              <th style={{ width: "10%" }}>Bus</th>
              <th style={{ width: "35%" }}>Name</th>
              <th style={{ width: "25%" }}>Type</th>
              <th>Notes</th>
            </tr>
          </thead>
          <tbody>
            {scene.buses.map((b) => (
              <tr key={`bus-${b.number}`}>
                <td>{b.number}</td>
                <td>{b.name}</td>
                <td>{b.type ?? ""}</td>
                <td>{b.notes ?? ""}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </Section>

      <Section title="3. DCA Groups">
        <table className="print-table">
          <thead>
            <tr>
              <th style={{ width: "10%" }}>DCA</th>
              <th style={{ width: "30%" }}>Name</th>
              <th>Assigned Channels</th>
            </tr>
          </thead>
          <tbody>
            {scene.dcas.map((d) => (
              <tr key={`dca-${d.number}`}>
                <td>{d.number}</td>
                <td>{d.name}</td>
                <td>{(d.assignedChannels ?? []).join(", ")}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </Section>

      <Section title="4. Output Patches">
        <table className="print-table">
          <thead>
            <tr>
              <th style={{ width: "20%" }}>Type</th>
              <th style={{ width: "10%" }}>#</th>
              <th style={{ width: "40%" }}>Source</th>
              <th>Notes</th>
            </tr>
          </thead>
          <tbody>
            {scene.outputs.map((o, i) => (
              <tr key={`out-${i}`}>
                <td>{o.outputType}</td>
                <td>{o.number}</td>
                <td>{o.source}</td>
                <td>{o.notes ?? ""}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </Section>

      <footer className="print-footer">
        Generated by X32/M32 RouteView — documentation tool, read-only.
      </footer>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="print-section">
      <h2>{title}</h2>
      {children}
    </section>
  );
}

function Stat({ label, value }: { label: string; value: number }) {
  return (
    <div className="print-stat">
      <div className="print-stat-value">{value}</div>
      <div className="print-stat-label">{label}</div>
    </div>
  );
}
